"""schemas package — Modular domain schemas with backward-compatible re-exports"""
from app.schemas.common import _OrmBase, Token, TokenData, DashboardStats
from app.schemas.users import UserBase, UserCreate, User, UserUpdate, UserChangePassword, OwnerPremiumGrantPayload, OwnerPremiumRevokePayload, TeacherPublicRegister
from app.schemas.student import StudentBase, StudentCreate, Student, StudentUpdate, StudentChangePassword, StudentPublicRegister, FaceValidationResult, FaceSampleResponse, ReEnrollmentRequestCreate, ReEnrollmentRequestResponse
from app.schemas.institution import InstitutionBrandingResponse, InstitutionCreate, InstitutionMasterKeyUpdate, InstitutionUpdate, DepartmentBase, DepartmentCreate, Department
from app.schemas.attendance import AttendanceBase, AttendanceCreate, Attendance, ManualAttendanceCreate, SubjectBase, SubjectCreate, SubjectResponse, ScheduleBase, ScheduleCreate, ScheduleResponse, SubjectAttendancePlan, WhatIfSimulationRequest, WhatIfSimulationResult, AttendancePlannerResponse, LowConfidenceReviewResponse, LowConfidenceResolvePayload, AttendanceInterventionResponse, AssignCounselorPayload, ResolveInterventionPayload, InterventionSummary, DisputeCreate, DisputeReviewPayload, DisputeEscalatePayload, DisputeCommentCreate, DisputeCommentResponse, DisputeResponse
from app.schemas.qr import FallbackSessionCreate, FallbackSessionResponse, ActiveRollingTokenResponse, ClaimQrPayload, ClaimPinPayload, FallbackClaimResult
from app.schemas.leave import LeaveRequestBase, LeaveRequestCreate, LeaveRequestResponse, LeaveStatusUpdate
from app.schemas.audit import AuditLogCreate, AuditLogResponse
from app.schemas.settings import SystemSettingsBase, SystemSettingsUpdate, SystemSettingsResponse, ReleaseUpdatePayload, ToggleUpdatePayload, ToggleBetaPayload, TriggerBuildPayload, BuildCallbackPayload, FeedbackCreate, FeedbackResponse
from app.schemas.device import AttendanceDeviceBase, AttendanceDeviceCreate, AttendanceDeviceUpdate, AttendanceDeviceResponse, DeviceHeartbeatPayload, DeviceFleetSummary
from app.schemas.calendar import CalendarEventBase, CalendarEventCreate, CalendarEventUpdate, CalendarEventResponse, ClassCancellationPayload, SubstituteTeacherPayload, CalendarAttendanceMetrics
from app.schemas.lms_staff import LmsConfigPayload, LmsConfigResponse, LmsSyncTriggerResponse, LmsSyncLogResponse, StaffAttendanceResponse, StaffPayrollCalculatePayload, StaffPayrollResponse

__all__ = ['_OrmBase', 'Token', 'TokenData', 'DashboardStats', 'UserBase', 'UserCreate', 'User', 'UserUpdate', 'UserChangePassword', 'OwnerPremiumGrantPayload', 'OwnerPremiumRevokePayload', 'TeacherPublicRegister', 'StudentBase', 'StudentCreate', 'Student', 'StudentUpdate', 'StudentChangePassword', 'StudentPublicRegister', 'FaceValidationResult', 'FaceSampleResponse', 'ReEnrollmentRequestCreate', 'ReEnrollmentRequestResponse', 'InstitutionBrandingResponse', 'InstitutionCreate', 'InstitutionMasterKeyUpdate', 'InstitutionUpdate', 'DepartmentBase', 'DepartmentCreate', 'Department', 'AttendanceBase', 'AttendanceCreate', 'Attendance', 'ManualAttendanceCreate', 'SubjectBase', 'SubjectCreate', 'SubjectResponse', 'ScheduleBase', 'ScheduleCreate', 'ScheduleResponse', 'SubjectAttendancePlan', 'WhatIfSimulationRequest', 'WhatIfSimulationResult', 'AttendancePlannerResponse', 'LowConfidenceReviewResponse', 'LowConfidenceResolvePayload', 'AttendanceInterventionResponse', 'AssignCounselorPayload', 'ResolveInterventionPayload', 'InterventionSummary', 'DisputeCreate', 'DisputeReviewPayload', 'DisputeEscalatePayload', 'DisputeCommentCreate', 'DisputeCommentResponse', 'DisputeResponse', 'FallbackSessionCreate', 'FallbackSessionResponse', 'ActiveRollingTokenResponse', 'ClaimQrPayload', 'ClaimPinPayload', 'FallbackClaimResult', 'LeaveRequestBase', 'LeaveRequestCreate', 'LeaveRequestResponse', 'LeaveStatusUpdate', 'AuditLogCreate', 'AuditLogResponse', 'SystemSettingsBase', 'SystemSettingsUpdate', 'SystemSettingsResponse', 'ReleaseUpdatePayload', 'ToggleUpdatePayload', 'ToggleBetaPayload', 'TriggerBuildPayload', 'BuildCallbackPayload', 'FeedbackCreate', 'FeedbackResponse', 'AttendanceDeviceBase', 'AttendanceDeviceCreate', 'AttendanceDeviceUpdate', 'AttendanceDeviceResponse', 'DeviceHeartbeatPayload', 'DeviceFleetSummary', 'CalendarEventBase', 'CalendarEventCreate', 'CalendarEventUpdate', 'CalendarEventResponse', 'ClassCancellationPayload', 'SubstituteTeacherPayload', 'CalendarAttendanceMetrics', 'LmsConfigPayload', 'LmsConfigResponse', 'LmsSyncTriggerResponse', 'LmsSyncLogResponse', 'StaffAttendanceResponse', 'StaffPayrollCalculatePayload', 'StaffPayrollResponse']
