/** All 8 levels × table rows — 56 extreme features */
export const EXTREME_LEVELS = [
  {
    id: 1,
    title: 'Pro App Feel',
    emoji: '⚡',
    features: [
      { id: 'live-board', name: 'Zero-latency Live Board', method: 'GET', path: '/level1/live-board', desc: 'Campus-wide live attendance feed' },
      { id: 'role-home', name: 'Smart Home per Role', method: 'GET', path: '/level1/role-home/teacher', pathVar: 'role', desc: 'Role-based widget layout' },
      { id: 'micro-interactions', name: 'Micro-interactions', method: 'GET', path: '/level1/micro-interactions', desc: 'Haptics, sounds, animations' },
      { id: 'search-index', name: 'Universal Search (Cmd+K)', method: 'GET', path: '/level1/search-index', query: true, desc: 'Search students & shortcuts' },
      { id: 'theme-mode', name: 'Dark/Light/AMOLED + Dyslexia', method: 'GET', path: '/level1/theme-mode', postPath: '/level1/theme-mode', desc: 'Accessibility theme modes' },
      { id: 'custom-spring', name: 'Custom Spring Animations', method: 'POST', path: '/level1/custom-spring', body: { enabled: true }, desc: 'Physics-based UI spring transitions for elements' },
    ],
  },
  {
    id: 2,
    title: 'Attendance Core',
    emoji: '🎯',
    features: [
      { id: 'biometric-modes', name: 'Multi-modal Biometric', method: 'GET', path: '/level2/biometric-modes', desc: 'Face, NFC, voice, RFID modes' },
      { id: 'passive-attendance', name: 'Continuous Passive Attendance', method: 'POST', path: '/level2/passive-attendance/toggle', body: { enabled: true }, desc: 'Classroom auto-scan toggle' },
      { id: 'anti-spoof', name: 'Anti-spoof AI 3.0', method: 'GET', path: '/level2/anti-spoof/status', desc: 'Deepfake & replay detection' },
      { id: 'seat-map', name: 'Seat-map Attendance', method: 'GET', path: '/level2/seat-map', desc: 'Classroom seat occupancy grid' },
      { id: 'buddy-attendance', name: 'Buddy Attendance', method: 'POST', path: '/level2/buddy-attendance', body: { student_ids: [] }, needsStudentIds: true, desc: 'Mark group in one action' },
      { id: 'blockchain', name: 'Blockchain Attendance Hash', method: 'GET', path: '/level2/blockchain/verify', postPath: '/level2/blockchain/append', desc: 'Tamper-proof hash chain' },
      { id: 'nfc', name: 'NFC Student ID Cards', method: 'POST', path: '/level2/nfc/register', body: { card_id: 'CARD-001', roll: '1' }, inputs: ['card_id', 'roll'], desc: 'Tap card instant mark' },
      { id: 'ble-beacon', name: 'BLE Beacon Classrooms (Teacher Control)', method: 'POST', path: '/level2/ble/beacon', body: { room: 'Room 101', enabled: false }, inputs: ['room'], desc: 'Toggle BLE beacon manually (default OFF)' },
    ],
  },
  {
    id: 3,
    title: 'AI Extreme',
    emoji: '🧠',
    features: [
      { id: 'copilot-pro', name: 'Attendance Copilot Pro', method: 'POST', path: '/level3/copilot-pro', body: { question: 'Is semester ka trend kya hai?' }, queryField: 'question', desc: 'AI charts & PDF hints' },
      { id: 'nl-rule', name: 'Natural Language Rules', method: 'POST', path: '/level3/nl-rule', body: { text: '3 din absent ho to parent ko WhatsApp' }, queryField: 'text', adminOnly: true, desc: 'Type rule in plain Hindi/English' },
      { id: 'cv-analytics', name: 'Computer Vision Analytics', method: 'GET', path: '/level3/cv-analytics', desc: 'Attention & engagement scores' },
      { id: 'auto-timetable', name: 'Auto Timetable Generator', method: 'POST', path: '/level3/auto-timetable', adminOnly: true, desc: 'AI-optimized period slots' },
      { id: 'voice-only', name: 'Voice-only Mode', method: 'POST', path: '/level3/voice-only/toggle', body: { enabled: true }, desc: 'Mark by voice offline-ready' },
      { id: 'document-ai', name: 'Document AI (Leave)', method: 'UPLOAD', path: '/level3/document-ai', desc: 'Medical cert auto review' },
      { id: 'fraud-detection', name: 'Fraud Detection ML', method: 'GET', path: '/level3/fraud-detection', adminOnly: true, desc: 'Proxy & duplicate scan alerts' },
      { id: 'emotion-analytics', name: 'Emotion-Aware Attendance', method: 'POST', path: '/level3/emotion-analytics', body: { student_id: '1', mood: 'neutral' }, desc: 'Check student mood (happy, neutral, tired) on scan' },
      { id: 'multiface-scan', name: 'Multi-Face Batch Scan', method: 'POST', path: '/level3/multiface-scan', body: { faces_count: 3 }, desc: 'Verify and check in multiple faces in parallel' },
      { id: 'face-aging-adapt', name: 'Face Aging & Beard Adaptation', method: 'POST', path: '/level3/face-aging-adapt', body: { student_id: '1', appearance_changes: ['beard', 'glasses'] }, desc: 'Adapt SFace embeddings to match changed features' },
      { id: 'lowlight-reconstruct', name: 'Low-Light Reconstruction', method: 'POST', path: '/level3/lowlight-reconstruct', body: { lux_level: 15.0 }, desc: 'Generative contrast CLAHE boost for dark settings' },
      { id: 'gaze-tracking', name: 'Gaze Focus Analysis', method: 'POST', path: '/level3/gaze-tracking', body: { horizontal_deg: 2.1, vertical_deg: 1.0, blink: false }, desc: 'Validate active camera gaze focus attention' },
      { id: 'hinglish-copilot', name: 'Hinglish AI Voice Copilot', method: 'POST', path: '/level3/hinglish-copilot', body: { query: 'aaj kaun absent hai?' }, queryField: 'query', desc: 'Gemini-powered Hinglish conversational queries' },
      { id: 'perf-diagnostics', name: 'Real-time Diagnostics Graph', method: 'GET', path: '/level3/perf-diagnostics', desc: 'Live GPU, VRAM, and alignment inference stats' },
    ],
  },
  {
    id: 4,
    title: 'Student / Parent Ecosystem',
    emoji: '👨‍👩‍👧',
    features: [
      { id: 'parent-superapp', name: 'Parent Super-app', method: 'GET', path: '/level4/parent-superapp', desc: 'Attendance + fees + bus modules' },
      { id: 'student-wallet', name: 'Student Life Wallet', method: 'GET', path: '/level4/student-life-wallet', desc: 'Streaks, badges, leaderboard' },
      { id: 'bus-tracking', name: 'Bus Tracking', method: 'GET', path: '/level4/bus-tracking', desc: 'Live bus ETA & routes' },
      { id: 'digital-id', name: 'Digital ID + QR Rotate', method: 'GET', path: '/level4/digital-id', desc: 'Wallet-style rotating QR card' },
      { id: 'peer-groups', name: 'Peer Study Groups', method: 'GET', path: '/level4/peer-groups', postPath: '/level4/peer-group', postBody: { name: 'CSE Study Group', members: [] }, desc: 'Class groups & challenges' },
      { id: 'mood-checkin', name: 'Mental Health Check-in', method: 'POST', path: '/level4/mood-checkin', body: { mood: 'okay', note: '' }, moodPicker: true, desc: 'Daily mood → counselor alert' },
      { id: 'scholarship', name: 'Scholarship Eligibility AI', method: 'GET', path: '/level4/scholarship-eligibility/1', pathSuffix: true, needsStudentId: true, desc: 'Attendance % eligibility check' },
    ],
  },
  {
    id: 5,
    title: 'Institution Enterprise',
    emoji: '🏛️',
    features: [
      { id: 'saas-control', name: 'Multi-tenant SaaS Control', method: 'GET', path: '/level5/saas-control', adminOnly: true, desc: 'All colleges one dashboard' },
      { id: 'white-label-store', name: 'White-label App Store', method: 'GET', path: '/level5/white-label-store', desc: 'Branded store listing assets' },
      { id: 'naac-export', name: 'NAAC / NBA Compliance', method: 'DOWNLOAD', path: '/level5/naac-export', adminOnly: true, desc: 'One-click accreditation report' },
      { id: 'hod-war-room', name: 'HOD War Room', method: 'GET', path: '/level5/hod-war-room', desc: 'Department live heatmap' },
      { id: 'principal-cc', name: 'Principal Command Center', method: 'GET', path: '/level5/principal-command-center', adminOnly: true, desc: 'TV mode campus stats' },
      { id: 'gov-api', name: 'Government API Sync', method: 'POST', path: '/level5/gov-api/sync', adminOnly: true, desc: 'Education registry sync' },
      { id: 'payroll-export', name: 'Payroll Integration', method: 'GET', path: '/level5/payroll-export', adminOnly: true, desc: 'Teacher hours for salary' },
      { id: 'lab-inventory', name: 'Lab Inventory + Session', method: 'GET', path: '/level5/lab-inventory', desc: 'Lab capacity & bookings' },
    ],
  },
  {
    id: 6,
    title: 'Security & Trust',
    emoji: '🔐',
    features: [
      { id: 'soc2-audit', name: 'SOC2-style Audit Trail', method: 'GET', path: '/level6/soc2-audit', adminOnly: true, desc: 'Who changed what & when' },
      { id: 'encryption', name: 'End-to-end Encryption', method: 'GET', path: '/level6/encryption-status', desc: 'Embeddings AES-256 at rest' },
      { id: 'gdpr-consent', name: 'GDPR / DPDP Consent', method: 'GET', path: '/level6/gdpr-consent', postPath: '/level6/gdpr-consent', desc: 'Biometric consent versioning' },
      { id: 'security-headers', name: 'Pen-test Ready Headers', method: 'GET', path: '/level6/security-headers', desc: 'CSP, HSTS, rate limits' },
      { id: 'abac', name: 'RBAC + ABAC Policies', method: 'POST', path: '/level6/abac-check', body: { resource: 'scanner' }, desc: 'Context-aware access check' },
      { id: 'disaster-recovery', name: 'Disaster Recovery', method: 'GET', path: '/level6/disaster-recovery', desc: 'RPO/RTO multi-region backup' },
      { id: 'siem-export', name: 'SIEM Integration', method: 'DOWNLOAD', path: '/level6/siem-export', adminOnly: true, desc: 'Splunk/Datadog log export' },
    ],
  },
  {
    id: 7,
    title: 'Extreme / Futuristic',
    emoji: '🛸',
    features: [
      { id: 'ar-overlay', name: 'AR Classroom Overlay', method: 'GET', path: '/level7/ar-overlay-config', desc: 'Floating names on faces' },
      { id: 'metaverse-kiosk', name: 'Metaverse Attendance Kiosk', method: 'POST', path: '/level7/metaverse-kiosk', body: { enabled: true }, desc: 'VR exam hall check-in' },
      { id: 'smartwatch', name: 'Smartwatch Mark', method: 'GET', path: '/level7/smartwatch', desc: 'Wear OS / watchOS quick present' },
      { id: 'satellite-geofence', name: 'Satellite Geofence', method: 'POST', path: '/level7/satellite-geofence', body: { radius_m: 500 }, adminOnly: true, desc: 'Outdoor camp attendance' },
      { id: 'drone-scan', name: 'Drone Perimeter Scan', method: 'GET', path: '/level7/drone-scan', desc: 'Large event coverage sim' },
      { id: 'emotion-alerts', name: 'Emotion-aware Alerts', method: 'GET', path: '/level7/emotion-alerts', desc: 'Absent + mood → counselor' },
      { id: 'digital-twin', name: 'Digital Twin Campus', method: 'GET', path: '/level7/digital-twin', desc: '3D density by department' },
      { id: 'proctoring', name: 'AI Proctoring Mode', method: 'POST', path: '/level7/proctoring/start', body: { exam_name: 'Final Exam' }, desc: 'Face + tab + audio monitor' },
    ],
  },
  {
    id: 8,
    title: 'Monetization & Scale',
    emoji: '💰',
    features: [
      { id: 'usage-meter', name: 'Usage-based Billing', method: 'GET', path: '/level8/usage-meter', desc: 'Per student / scan pricing' },
      { id: 'marketplace', name: 'Marketplace Plugins', method: 'GET', path: '/level8/marketplace', desc: 'Third-party themes & reports' },
      { id: 'developer-portal', name: 'API Developer Portal', method: 'GET', path: '/level8/developer-portal', adminOnly: true, desc: 'SDK, webhooks, API keys' },
      { id: 'franchise', name: 'Franchise Mode', method: 'GET', path: '/level8/franchise', adminOnly: true, desc: 'Branch-wise analytics' },
      { id: 'affiliate', name: 'Affiliate / Reseller', method: 'POST', path: '/level8/affiliate', body: { name: 'Partner' }, desc: 'Distributor commission codes' },
      { id: 'sla-enterprise', name: 'SLA Enterprise Tier', method: 'GET', path: '/level8/sla-enterprise', desc: '99.9% uptime status page' },
    ],
  },
];

export const TOTAL_EXTREME_FEATURES = EXTREME_LEVELS.reduce((n, l) => n + l.features.length, 0);
